services:
  backend:
    build: ./backend
    ports: 
    - "8080:8080"
    env_file:
    - ./frontend/.env
    environment:
    - DOCKER=true


  frontend:
    build: ./frontend
    ports: 
    - "5173:5173"
    environment:
    - DOCKER=true
